
[terminal.shell]
program = "/usr/bin/fish"
args =[
    "-c",
    "fastfetch --logo-type small && fish"
]

[font]
size = 8
normal = { family = "JetBrainsMono Nerd Font", style="Regular" }

[window]
padding = { x = 4, y = 2 }

[general]
import = [
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
  "~/.config/alacritty/themes/dracula.toml"
]

[terminal]
#dynamic_padding = true
