[terminal.shell]
program = "fish"
args =[
    "-c",
    "fish"
]

[font]
size = 11
normal = { family = "FiraCode Nerd Font", style="Regular" }

[window]
#padding = { x = 4, y = 2 }
dynamic_padding = true

[general]
import = [
    #"~/.config/alacritty/themes/catppuccin-mocha.toml"
  "~/.config/alacritty/themes/dracula.toml"
]

[terminal]
#dynamic_padding = true
